services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urc

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urc
  
  ollama:
    build:
      context: .
      dockerfile: images/ollama.Dockerfile
    env_file:
      - .env
    ports:
      - "11434:11434"
    networks:
      - urc

  app:
    build:
      context: .
      dockerfile: images/app.Dockerfile
    ports:
      - "9696:9696"
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - ollama
      - postgres
    networks:
      - urc

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
    depends_on:
      - postgres
    networks:
      - urc

volumes:
  postgres_data:
  grafana_data:

networks:
  urc:
    driver: bridge